In [ ]:
import numpy as np

number_vector = np.array([1, 2, 3, 4])
number_vector.shape

(4,)

In [ ]:
number_matrix = np.array([[1, 2, 3], [4, 5, 6]])
number_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
number_matrix.shape

(2, 3)

In [ ]:
number_matrix.shape

(2, 3)

In [ ]:
number_3D_matrix = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[1, 2, 3], [4, 5, 6]]
])

number_3D_matrix

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
number_3D_matrix.shape

(2, 2, 3)

In [ ]:
number_1D_zeros = np.zeros((10, ))
number_1D_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
number_1D_ones = np.ones((3, ))
number_1D_ones

array([1., 1., 1.])

In [ ]:
number_1D_sevens = np.full((6, ), 7)
number_1D_sevens

array([7, 7, 7, 7, 7, 7])

In [ ]:
number_2D_zeros = np.zeros((7, 7))
number_2D_zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
number_2D_ones = np.ones((6, 5))
number_2D_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
number_2D_eights = np.full((8, 8), 8)
number_2D_eights

array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]])

In [ ]:
number_3D_zeros = np.zeros((4, 2, 3))
number_3D_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
number_3D_ones = np.ones((3, 3, 4))
number_3D_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
number_3D_twenties = np.full((3, 2, 7), 20)
number_3D_twenties

array([[[20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20]]])

In [ ]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
number_1D_range_10 = np.arange(10)
number_1D_range_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
number_1D_range_20 = np.arange(2, 10)
number_1D_range_20

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
number_1D_range_30 = np.arange(0, 30, 2)
number_1D_range_30

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
np.random.random((10, 5))

array([[0.61662312, 0.17713518, 0.23823712, 0.59703783, 0.14801616],
       [0.0226789 , 0.19728253, 0.20106569, 0.85714463, 0.46551641],
       [0.92117106, 0.56962923, 0.43199115, 0.17843184, 0.81374315],
       [0.09711314, 0.48988399, 0.14060834, 0.93076241, 0.94545909],
       [0.15532214, 0.97798569, 0.64077105, 0.10945464, 0.25539568],
       [0.87796292, 0.08968279, 0.39623416, 0.40186325, 0.96217182],
       [0.07517684, 0.97550073, 0.65338355, 0.77461443, 0.0811847 ],
       [0.70219456, 0.29082929, 0.37419561, 0.3935547 , 0.30337667],
       [0.6206354 , 0.51321767, 0.4065515 , 0.62297902, 0.41657627],
       [0.10910138, 0.21932602, 0.47915055, 0.75297775, 0.97130807]])

In [ ]:
number_2D = np.array([[4,5,6], [7, 8, 9]])
number_2D[1]

array([7, 8, 9])

In [ ]:
number_2D[-1]

array([7, 8, 9])

In [ ]:
number_2D[:, 0] # -> Dấu : biển hiện việc duyệt qua tất cả các hàng, qua mỗi hàng ta lấy phần tử đầu tiên

array([4, 7])

In [ ]:
number_2D[:, -1]

array([6, 9])

In [ ]:
numbers_1D = np.array([1, 2, 3])
numbers_1D + 3

array([4, 5, 6])

In [ ]:
x = np.array([
    [6, 9, 10],
    [15, 18, 20],
])

y = np.array([
    [2],
    [4],
])

x+y

array([[ 8, 11, 12],
       [19, 22, 24]])

In [ ]:
numbers_3D = np.random.random((2, 3, 2))
numbers_3D

array([[[0.71969179, 0.51104752],
        [0.67358903, 0.08228475],
        [0.76810016, 0.65846479]],

       [[0.14235369, 0.33656085],
        [0.04172224, 0.91742326],
        [0.97150559, 0.41101997]]])

In [ ]:
for item in np.nditer(numbers_3D):
    print(item)

0.7196917858169634
0.5110475199292992
0.67358902587886
0.0822847533466643
0.7681001600407105
0.6584647906695021
0.1423536903229835
0.33656085393254354
0.041722238585728655
0.9174232587495578
0.9715055908736389
0.41101997335596685


In [ ]:
numbers_2D = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

numbers_2D.shape

(2, 4)

In [ ]:
numbers_3D = numbers_2D.reshape(2, 2, 2)
numbers_3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
numbers = np.random.random((3, 3, 3))
numbers

array([[[0.04157186, 0.40498152, 0.85823391],
        [0.52406262, 0.64314001, 0.21880488],
        [0.24168141, 0.86401685, 0.7975565 ]],

       [[0.26017827, 0.25698103, 0.92635252],
        [0.85077853, 0.09967426, 0.06687438],
        [0.84896919, 0.99066311, 0.45257018]],

       [[0.85515123, 0.4966046 , 0.79077929],
        [0.00477358, 0.74511361, 0.45806714],
        [0.06828814, 0.69667332, 0.39377167]]])

In [ ]:
numbers.shape

(3, 3, 3)

In [ ]:
flattened_numbers = numbers.flatten()
flattened_numbers.shape

(27,)

In [ ]:
flattened_numbers

array([0.04157186, 0.40498152, 0.85823391, 0.52406262, 0.64314001,
       0.21880488, 0.24168141, 0.86401685, 0.7975565 , 0.26017827,
       0.25698103, 0.92635252, 0.85077853, 0.09967426, 0.06687438,
       0.84896919, 0.99066311, 0.45257018, 0.85515123, 0.4966046 ,
       0.79077929, 0.00477358, 0.74511361, 0.45806714, 0.06828814,
       0.69667332, 0.39377167])

In [ ]:
numbers_2D = np.array(([1,2],[3,4]))
numbers_2D.shape

(2, 2)

In [ ]:
numbers_3D_axis_0 = np.expand_dims(numbers_2D, axis=0)
numbers_3D_axis_0.shape

(1, 2, 2)

In [ ]:
numbers_3D_axis_0

array([[[1, 2],
        [3, 4]]])

In [ ]:
numbers_3D_axis_1 = np.expand_dims(numbers_2D, axis=1)
numbers_3D_axis_1.shape

(2, 1, 2)

In [ ]:
numbers_2D = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
transposed_numbers_1 = numbers_2D.T
transposed_numbers_1

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])